#!/bin/sh

DIR=/home/roberto/aratha

if
  [ -z $2 ]
then
  s=G-Strings
else
  s=$2
fi
SOLVER=$s npm run analyze -- $1

ilog=`basename $1 | awk -F"." '{print $1}'`.inputlog.json
mv inputlog.json $ilog

nyc node $DIR/bin/replay-inputs.js $1

#echo "===== SOURCE ====="; cat $1 | awk '{print NR,"\t",$0}'

echo "===== INPUT ===== ";  cat $ilog

nyc report --reporter=html

xdg-open $DIR/coverage/index.html

rm $ilog

